export const GRID_SIZE = 16;
export const BASE_TICK_DELAY = 170;
export const STORAGE_KEY = "ai-poetry-snake-state-v2";
export const STORAGE_VERSION = 2;

export const DIRECTION_MAP = {
  ArrowUp: { x: 0, y: -1 },
  ArrowDown: { x: 0, y: 1 },
  ArrowLeft: { x: -1, y: 0 },
  ArrowRight: { x: 1, y: 0 },
};

export const SOURCE_LABELS = {
  fallback: "本地降级",
  zhipu: "GLM",
  minimax: "MiniMax",
  volcengine: "豆包图片",
  hybrid: "混合模式",
};

export const moods = {
  meadow: {
    label: "晨林",
    bgTop: "#0f1726",
    bgBottom: "#1f2f27",
    text: "#f5fff9",
    muted: "#a7c8b3",
    accent: "#a8ff8b",
    accentSoft: "rgba(168, 255, 139, 0.16)",
    accentWarm: "#ffd884",
    snake: "#72f2bd",
    snakeHead: "#dcfff0",
    boardTop: "#102016",
    boardBottom: "#24392a",
    grid: "rgba(226, 255, 236, 0.08)",
    glow: "rgba(168, 255, 139, 0.28)",
  },
  wind: {
    label: "风场",
    bgTop: "#0d1a2d",
    bgBottom: "#183449",
    text: "#eef8ff",
    muted: "#9fc5db",
    accent: "#7dd7ff",
    accentSoft: "rgba(125, 215, 255, 0.16)",
    accentWarm: "#d5f1ff",
    snake: "#91e8ff",
    snakeHead: "#e5fbff",
    boardTop: "#102035",
    boardBottom: "#22435d",
    grid: "rgba(227, 247, 255, 0.08)",
    glow: "rgba(125, 215, 255, 0.26)",
  },
  night: {
    label: "夜幕",
    bgTop: "#0c1124",
    bgBottom: "#1d2855",
    text: "#f5f5ff",
    muted: "#afb5ef",
    accent: "#9b8cff",
    accentSoft: "rgba(155, 140, 255, 0.18)",
    accentWarm: "#ddd4ff",
    snake: "#86a1ff",
    snakeHead: "#dde4ff",
    boardTop: "#121936",
    boardBottom: "#2d3970",
    grid: "rgba(232, 234, 255, 0.08)",
    glow: "rgba(155, 140, 255, 0.3)",
  },
  dream: {
    label: "梦境",
    bgTop: "#221227",
    bgBottom: "#50315c",
    text: "#fff6fd",
    muted: "#ddbfdd",
    accent: "#ff90cc",
    accentSoft: "rgba(255, 144, 204, 0.18)",
    accentWarm: "#ffd7ee",
    snake: "#ffb1d8",
    snakeHead: "#fff0f7",
    boardTop: "#2d1731",
    boardBottom: "#5e3870",
    grid: "rgba(255, 236, 248, 0.08)",
    glow: "rgba(255, 144, 204, 0.3)",
  },
  cosmic: {
    label: "深空",
    bgTop: "#0b1020",
    bgBottom: "#152744",
    text: "#f1f7ff",
    muted: "#9eb7d7",
    accent: "#67dfff",
    accentSoft: "rgba(103, 223, 255, 0.18)",
    accentWarm: "#d0f7ff",
    snake: "#79f4e2",
    snakeHead: "#d8fff9",
    boardTop: "#11172f",
    boardBottom: "#1f3a5e",
    grid: "rgba(232, 244, 255, 0.08)",
    glow: "rgba(103, 223, 255, 0.3)",
  },
  ink: {
    label: "水墨",
    bgTop: "#131313",
    bgBottom: "#34373c",
    text: "#faf7f0",
    muted: "#c9c2b8",
    accent: "#c3d0e0",
    accentSoft: "rgba(195, 208, 224, 0.16)",
    accentWarm: "#f0eadf",
    snake: "#d7ddd8",
    snakeHead: "#ffffff",
    boardTop: "#1d1f22",
    boardBottom: "#44484d",
    grid: "rgba(255, 248, 239, 0.08)",
    glow: "rgba(195, 208, 224, 0.2)",
  },
};

export const themes = {
  fairytale: {
    label: "童话",
    baseMood: "meadow",
    introTitle: "童话森林已经醒来",
    introText: "第一批词语会由系统预热，吃到词后会异步生成诗句和配图。",
    fallbackWords: [
      { word: "鹿", association: "晨露", scene: "林间空地", art: "林中小鹿" },
      { word: "灯", association: "柔光", scene: "树洞门口", art: "发光的树洞" },
      { word: "蝶", association: "轻盈", scene: "花丛边缘", art: "蝶影盘旋" },
      { word: "湖", association: "倒影", scene: "雾气边缘", art: "静湖微光" },
      { word: "露", association: "清亮", scene: "草叶尖端", art: "露珠闪烁" },
      { word: "风", association: "树冠波纹", scene: "林顶", art: "风穿过树梢", magic: true, mood: "wind" },
      { word: "夜", association: "深蓝", scene: "林间小径", art: "夜色压低", magic: true, mood: "night" },
      { word: "梦", association: "柔软回声", scene: "月下湖面", art: "梦雾浮动", magic: true, mood: "dream" },
    ],
  },
  scifi: {
    label: "科幻",
    baseMood: "cosmic",
    introTitle: "航道已接入深空",
    introText: "系统会把吃到的词写成一段航行记录，并尝试同步生成舷窗画面。",
    fallbackWords: [
      { word: "舱", association: "白噪", scene: "观景窗前", art: "静默舱壁" },
      { word: "轨", association: "蓝色尾迹", scene: "引力边缘", art: "轨道弧线" },
      { word: "核", association: "冷光", scene: "反应堆旁", art: "能量核心" },
      { word: "镜", association: "折射", scene: "信号塔顶", art: "镜面折光" },
      { word: "锚", association: "定位", scene: "星云边缘", art: "光锚定点" },
      { word: "风", association: "电离层噪点", scene: "航道外壳", art: "气流擦过船体", magic: true, mood: "wind" },
      { word: "夜", association: "深空静压", scene: "星门背后", art: "夜幕压低舷窗", magic: true, mood: "night" },
      { word: "梦", association: "休眠回波", scene: "睡眠舱内", art: "梦像星云漂移", magic: true, mood: "dream" },
    ],
  },
  tang: {
    label: "唐诗",
    baseMood: "ink",
    introTitle: "江月正在起笔",
    introText: "这局会沿着古诗意境推进，词语被吃掉后会化成一行近似题咏的句子。",
    fallbackWords: [
      { word: "舟", association: "轻摇", scene: "江心", art: "孤舟过水" },
      { word: "江", association: "水声", scene: "远岸", art: "江色铺开" },
      { word: "月", association: "清辉", scene: "桥边夜色", art: "江月照桥" },
      { word: "山", association: "远黛", scene: "云后", art: "山影沉静" },
      { word: "柳", association: "软烟", scene: "长堤", art: "柳色临风" },
      { word: "风", association: "帆影轻摇", scene: "江面中央", art: "风过芦花", magic: true, mood: "wind" },
      { word: "夜", association: "钟声渐远", scene: "城外江岸", art: "夜色压江", magic: true, mood: "night" },
      { word: "梦", association: "未寄心事", scene: "客舍枕边", art: "梦回故里", magic: true, mood: "dream" },
    ],
  },
};
